export const LABELS = [
  "User",
  "Post",
  "Comment",
  "Hashtag",
  "Group",
  "Message",
  "Media",
  "Notification",
];

export const RELATIONSHIP_TYPES = [
  "FOLLOWS",
  "BLOCKED",
  "MEMBER_OF",
  "POSTED",
  "LIKED",
  "COMMENTED",
  "SENT",
  "TAGGED_WITH",
  "CONTAINS",
  "REPLIED_TO",
  "HAS_MEDIA",
  "RECEIVED",
  "ABOUT",
  "SAVED",
  "SHARED_IN",
];

export const ID_PROPERTY = {
  User: "userId",
  Post: "postId",
  Comment: "commentId",
  Hashtag: "name",
  Group: "groupId",
  Message: "messageId",
  Media: "mediaId",
  Notification: "notificationId",
};

export const LABEL_TEMPLATES = {
  User: {
    userId: "u_demo",
    username: "demo",
    email: "demo@demo.com",
    bio: "",
    profilePicUrl: "",
    isVerified: false,
    followersCount: 0,
    followingCount: 0,
    interests: [],
    birthDate: "2000-01-01",
    createdAt: "2026-05-05",
  },
  Post: {
    postId: "p_demo",
    content: "demo",
    location: "GT",
    mediaUrls: [],
    isPublic: true,
    likesCount: 0,
    commentsCount: 0,
    createdAt: "2026-05-05",
    updatedAt: "2026-05-05",
  },
  Comment: {
    commentId: "c_demo",
    content: "demo",
    isEdited: false,
    likesCount: 0,
    sentiment: "neutral",
    createdAt: "2026-05-05",
    updatedAt: "2026-05-05",
  },
  Hashtag: {
    name: "demo",
    postsCount: 0,
    followersCount: 0,
    isTrending: false,
    relatedTopics: [],
    createdAt: "2026-05-05",
  },
  Group: {
    groupId: "g_demo",
    name: "demo",
    description: "",
    isPrivate: false,
    membersCount: 0,
    categories: [],
    createdAt: "2026-05-05",
  },
  Message: {
    messageId: "m_demo",
    content: "demo",
    isRead: false,
    mediaUrl: "",
    reactionType: "",
    sentAt: "2026-05-05",
    readAt: "2026-05-05",
  },
  Media: {
    mediaId: "md_demo",
    url: "https://x",
    type: "image",
    sizeKB: 1.5,
    format: "png",
    uploadedAt: "2026-05-05",
  },
  Notification: {
    notificationId: "nx_demo",
    type: "info",
    isRead: false,
    priority: "low",
    message: "",
    createdAt: "2026-05-05",
  },
};

export const REL_PROP_TEMPLATES = {
  FOLLOWS: { since: "2026-05-05", notificationsEnabled: true, mutualFriendsCount: 0 },
  BLOCKED: { blockedAt: "2026-05-05", reason: "spam", isPermanent: false },
  MEMBER_OF: { joinedAt: "2026-05-05", role: "member", contributionScore: 0.0 },
  POSTED: { postedAt: "2026-05-05", device: "web", location: "GT" },
  LIKED: { likedAt: "2026-05-05", reactionType: "like", isActive: true },
  COMMENTED: { commentedAt: "2026-05-05", isFirstComment: false, device: "web" },
  SENT: { sentAt: "2026-05-05", isEncrypted: true, channel: "direct" },
  TAGGED_WITH: { taggedAt: "2026-05-05", relevanceScore: 0.5, isPrimary: false },
  CONTAINS: { addedAt: "2026-05-05", isVisible: true, moderationStatus: "ok" },
  REPLIED_TO: { repliedAt: "2026-05-05", isDirectMention: false, notifiedParent: true },
  HAS_MEDIA: { attachedAt: "2026-05-05", isPrimary: true, caption: "" },
  RECEIVED: { receivedAt: "2026-05-05", isRead: false, notificationType: "info" },
  ABOUT: { linkedAt: "2026-05-05", context: "", targetType: "Post" },
  SAVED: { savedAt: "2026-05-05", note: "", isPrivate: false },
  SHARED_IN: { sharedAt: "2026-05-05", caption: "", visibleToMembers: true },
};

export const REL_ALLOWED_PAIRS = {
  FOLLOWS: [["User", "User"]],
  BLOCKED: [["User", "User"]],
  MEMBER_OF: [["User", "Group"]],
  POSTED: [["User", "Post"]],
  LIKED: [["User", "Post"], ["User", "Comment"]],
  COMMENTED: [["User", "Post"]],
  SENT: [["User", "Message"]],
  TAGGED_WITH: [["Post", "Hashtag"]],
  CONTAINS: [["Post", "Comment"]],
  REPLIED_TO: [["Comment", "Comment"]],
  HAS_MEDIA: [["Post", "Media"], ["Message", "Media"]],
  RECEIVED: [["User", "Notification"]],
  ABOUT: [["Notification", "Post"], ["Notification", "Comment"], ["Notification", "User"]],
  SAVED: [["User", "Post"]],
  SHARED_IN: [["Post", "Group"]],
};
